import { DemoAccount, RolePermissions, UserRole } from "@/types/auth";

export const DEMO_ACCOUNTS: DemoAccount[] = [
  {
    email: "lawyer@yrjr.app",
    password: "demo123",
    role: "lawyer",
    name: "Advocate Rajesh Kumar",
    displayTitle: "Senior Lawyer",
  },
  {
    email: "jr.lawyer@yrjr.app",
    password: "demo123",
    role: "junior_lawyer",
    name: "Priya Sharma",
    displayTitle: "Junior Lawyer",
  },
  {
    email: "assistant@yrjr.app",
    password: "demo123",
    role: "lawyer_assistant",
    name: "Rohit Gupta",
    displayTitle: "Legal Assistant",
  },
  {
    email: "helper@yrjr.app",
    password: "demo123",
    role: "law_office_helper",
    name: "Meera Singh",
    displayTitle: "Office Helper",
  },
  {
    email: "student@yrjr.app",
    password: "demo123",
    role: "law_student",
    name: "Arjun Patel",
    displayTitle: "Law Student",
  },
];

export const ROLE_PERMISSIONS: Record<UserRole, RolePermissions> = {
  lawyer: {
    canEditCases: true,
    canViewClientFolders: true,
    canAccessSecureVault: true,
    canUsePinboard: true,
    canViewTimeline: true,
    canUseFlashcards: true,
    canCompareSections: true,
    maxClients: 100,
    maxCases: 500,
  },
  junior_lawyer: {
    canEditCases: true,
    canViewClientFolders: true,
    canAccessSecureVault: true,
    canUsePinboard: true,
    canViewTimeline: true,
    canUseFlashcards: true,
    canCompareSections: true,
    maxClients: 50,
    maxCases: 200,
  },
  lawyer_assistant: {
    canEditCases: false,
    canViewClientFolders: true,
    canAccessSecureVault: false,
    canUsePinboard: true,
    canViewTimeline: true,
    canUseFlashcards: true,
    canCompareSections: true,
    maxClients: 25,
    maxCases: 100,
  },
  law_office_helper: {
    canEditCases: false,
    canViewClientFolders: false,
    canAccessSecureVault: false,
    canUsePinboard: true,
    canViewTimeline: false,
    canUseFlashcards: true,
    canCompareSections: true,
    maxClients: 0,
    maxCases: 0,
  },
  law_student: {
    canEditCases: false,
    canViewClientFolders: false,
    canAccessSecureVault: false,
    canUsePinboard: true,
    canViewTimeline: false,
    canUseFlashcards: true,
    canCompareSections: true,
    maxClients: 0,
    maxCases: 0,
  },
};

export const ROLE_DISPLAY_INFO = {
  lawyer: {
    title: "Senior Lawyer",
    description: "Full access to all legal features and client management",
    icon: "👨‍💼",
    color: "#8B5CF6",
  },
  junior_lawyer: {
    title: "Junior Lawyer",
    description: "Access to legal features with limited client capacity",
    icon: "👩‍🎓",
    color: "#06B6D4",
  },
  lawyer_assistant: {
    title: "Legal Assistant",
    description: "Support role with view access to cases and clients",
    icon: "👥",
    color: "#10B981",
  },
  law_office_helper: {
    title: "Office Helper",
    description: "Administrative support with basic feature access",
    icon: "📋",
    color: "#F59E0B",
  },
  law_student: {
    title: "Law Student",
    description: "Learning-focused access to educational features",
    icon: "📚",
    color: "#EF4444",
  },
} as const;
