export const INDIAN_LANGUAGES = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు" },
  { code: "mr", name: "Marathi", nativeName: "मराठी" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
  { code: "ur", name: "Urdu", nativeName: "اردو" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം" },
  { code: "or", name: "Odia", nativeName: "ଓଡ଼ିଆ" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
  { code: "as", name: "Assamese", nativeName: "অসমীয়া" },
];

export const USER_ROLES = [
  {
    id: "lawyer",
    title: "Lawyer",
    description: "Practicing advocate with Bar Council registration",
    icon: "briefcase",
    color: "#8B5CF6",
    requiresVerification: true,
  },
  {
    id: "junior_lawyer",
    title: "Junior Lawyer",
    description: "Recently qualified lawyer with limited experience",
    icon: "academic-cap",
    color: "#06B6D4",
    requiresVerification: true,
  },
  {
    id: "lawyer_assistant",
    title: "Lawyer Assistant",
    description: "Legal assistant supporting lawyer activities",
    icon: "user-group",
    color: "#10B981",
    requiresVerification: false,
  },
  {
    id: "law_office_helper",
    title: "Law Office Helper",
    description: "Administrative support in legal offices",
    icon: "clipboard-document",
    color: "#F59E0B",
    requiresVerification: false,
  },
  {
    id: "law_student",
    title: "Law Student",
    description: "Currently pursuing law degree",
    icon: "book-open",
    color: "#EF4444",
    requiresVerification: false,
  },
];

export const SUBSCRIPTION_PLANS = [
  {
    id: "monthly",
    title: "Monthly Plan",
    price: 299,
    duration: "1 month",
    features: [
      "Access to all court orders",
      "Basic search functionality",
      "Community access",
      "Daily quiz",
      "Email support",
    ],
    popular: false,
  },
  {
    id: "quarterly",
    title: "Quarterly Plan",
    price: 799,
    duration: "3 months",
    originalPrice: 897,
    features: [
      "All Monthly features",
      "Advanced search filters",
      "Voice assistant",
      "Priority messaging",
      "Case tracker",
      "Phone support",
    ],
    popular: true,
  },
  {
    id: "yearly",
    title: "Yearly Plan",
    price: 2999,
    duration: "12 months",
    originalPrice: 3588,
    features: [
      "All Quarterly features",
      "Unlimited document storage",
      "AI-powered insights",
      "Custom legal templates",
      "Priority customer support",
      "Legal consultation credits",
    ],
    popular: false,
  },
];

export const COURT_TYPES = [
  "Supreme Court",
  "High Court",
  "District Court",
  "Sessions Court",
  "Lok Adalat",
  "Family Court",
  "Consumer Court",
  "Labour Court",
  "Revenue Court",
  "Motor Accident Claims Tribunal",
];

export const LEGAL_SECTIONS = [
  {
    code: "IPC",
    name: "Indian Penal Code",
    description: "Criminal law provisions",
  },
  {
    code: "CrPC",
    name: "Criminal Procedure Code",
    description: "Criminal procedure guidelines",
  },
  {
    code: "BNS",
    name: "Bharatiya Nyaya Sanhita",
    description: "New criminal law code",
  },
  {
    code: "BNSS",
    name: "Bharatiya Nagarik Suraksha Sanhita",
    description: "New criminal procedure code",
  },
  {
    code: "CPC",
    name: "Civil Procedure Code",
    description: "Civil procedure guidelines",
  },
  {
    code: "Evidence Act",
    name: "Indian Evidence Act",
    description: "Rules of evidence",
  },
  {
    code: "Constitution",
    name: "Indian Constitution",
    description: "Fundamental law of India",
  },
];

export const LEGAL_CATEGORIES = [
  "Criminal Law",
  "Civil Law",
  "Family Law",
  "Corporate Law",
  "Labour Law",
  "Property Law",
  "Constitutional Law",
  "Tax Law",
  "Consumer Protection",
  "Environmental Law",
  "Intellectual Property",
  "Banking Law",
];

export const SPECIALIZATIONS = [
  "Criminal Defense",
  "Civil Litigation",
  "Family Law",
  "Corporate Law",
  "Immigration Law",
  "Real Estate",
  "Personal Injury",
  "Employment Law",
  "Tax Law",
  "Intellectual Property",
  "Environmental Law",
  "Banking & Finance",
  "Constitutional Law",
  "Consumer Protection",
  "Media & Entertainment",
  "Cyber Law",
];

export const LEGAL_PROCESSES = [
  {
    id: "fir",
    title: "How to File FIR",
    category: "Criminal Law",
    steps: [
      "Go to the nearest police station",
      "Provide detailed information about the incident",
      "Ensure FIR is registered and get a copy",
      "Keep all related documents safe",
    ],
    timeRequired: "1-2 hours",
    documents: ["Identity proof", "Address proof", "Evidence (if any)"],
  },
  {
    id: "bail",
    title: "Bail Application Process",
    category: "Criminal Law",
    steps: [
      "File bail application in appropriate court",
      "Prepare supporting documents",
      "Present case before magistrate/judge",
      "Comply with bail conditions if granted",
    ],
    timeRequired: "1-7 days",
    documents: ["Bail application", "Surety documents", "Identity proof"],
  },
  {
    id: "divorce",
    title: "Divorce Procedure",
    category: "Family Law",
    steps: [
      "File divorce petition in family court",
      "Serve notice to spouse",
      "Attend court hearings",
      "Complete legal formalities",
    ],
    timeRequired: "6 months - 2 years",
    documents: ["Marriage certificate", "Identity proof", "Address proof"],
  },
];

export const HOME_SECTIONS = [
  {
    id: "legal_pinboard",
    title: "Legal Pinboard",
    description: "Pin important notes and updates",
    icon: "push-pin",
    color: "#8B5CF6",
    route: "/(main)/legal-pinboard",
  },
  {
    id: "case_timeline",
    title: "Case Timeline",
    description: "Interactive case progress tracker",
    icon: "timeline",
    color: "#3B82F6",
    route: "/(main)/case-timeline",
  },
  {
    id: "secure_vault",
    title: "Secure Vault",
    description: "Encrypted notes with biometric access",
    icon: "shield-checkmark",
    color: "#10B981",
    route: "/(main)/secure-vault",
  },
  {
    id: "section_comparator",
    title: "IPC vs BNS",
    description: "Compare legal sections side-by-side",
    icon: "git-compare",
    color: "#F59E0B",
    route: "/(main)/section-comparator",
  },
  {
    id: "flashcards",
    title: "Legal Flashcards",
    description: "Micro-learning for law students",
    icon: "school",
    color: "#EC4899",
    route: "/(main)/flashcards",
  },
  {
    id: "client_folders",
    title: "Client Folders",
    description: "Organize cases by client",
    icon: "folder",
    color: "#06B6D4",
    route: "/(main)/client-folders",
  },
  {
    id: "court_orders",
    title: "Court Orders",
    description: "Recent court orders and judgments",
    icon: "document-text",
    color: "#EF4444",
    route: "/(main)/(tabs)/court-orders",
  },
  {
    id: "messaging",
    title: "Messaging",
    description: "Connect with legal professionals",
    icon: "chatbubbles",
    color: "#84CC16",
    route: "/(main)/(tabs)/messages",
  },
];

export const QUIZ_CATEGORIES = [
  "Constitutional Law",
  "Criminal Law",
  "Civil Law",
  "Family Law",
  "Corporate Law",
  "Labour Law",
  "Property Law",
  "Tax Law",
  "Evidence Law",
  "Procedure Code",
];

export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];
