export interface State {
  code: string;
  name: string;
  cities: string[];
}

export const INDIAN_STATES: State[] = [
  {
    code: "AP",
    name: "Andhra Pradesh",
    cities: [
      "Visakhapatnam",
      "Vijayawada",
      "Guntur",
      "Nellore",
      "Kurnool",
      "Rajahmundry",
      "Tirupati",
      "Anantapur",
      "Chittoor",
      "Eluru",
    ],
  },
  {
    code: "AR",
    name: "Arunachal Pradesh",
    cities: [
      "Itanagar",
      "Naharlagun",
      "Pasighat",
      "Tezpur",
      "Bomdila",
      "Ziro",
      "Along",
      "Tezu",
      "Changlang",
      "Namsai",
    ],
  },
  {
    code: "AS",
    name: "Assam",
    cities: [
      "Guwahati",
      "Silchar",
      "Dibrugarh",
      "Jorhat",
      "Nagaon",
      "Tinsukia",
      "Tezpur",
      "Bongaigaon",
      "Karimganj",
      "Sivasagar",
    ],
  },
  {
    code: "BR",
    name: "Bihar",
    cities: [
      "Patna",
      "Gaya",
      "Bhagalpur",
      "Muzaffarpur",
      "Purnia",
      "Darbhanga",
      "Bihar Sharif",
      "Arrah",
      "Begusarai",
      "Katihar",
    ],
  },
  {
    code: "CT",
    name: "Chhattisgarh",
    cities: [
      "Raipur",
      "Bhilai",
      "Bilaspur",
      "Korba",
      "Durg",
      "Rajnandgaon",
      "Jagdalpur",
      "Raigarh",
      "Ambikapur",
      "Mahasamund",
    ],
  },
  {
    code: "DL",
    name: "Delhi",
    cities: [
      "New Delhi",
      "Delhi",
      "Dwarka",
      "Rohini",
      "Janakpuri",
      "Laxmi Nagar",
      "Karol Bagh",
      "Connaught Place",
      "Saket",
      "Vasant Kunj",
    ],
  },
  {
    code: "GA",
    name: "Goa",
    cities: [
      "Panaji",
      "Margao",
      "Vasco da Gama",
      "Mapusa",
      "Ponda",
      "Bicholim",
      "Curchorem",
      "Sanquelim",
      "Cuncolim",
      "Quepem",
    ],
  },
  {
    code: "GJ",
    name: "Gujarat",
    cities: [
      "Ahmedabad",
      "Surat",
      "Vadodara",
      "Rajkot",
      "Bhavnagar",
      "Jamnagar",
      "Gandhinagar",
      "Junagadh",
      "Anand",
      "Morbi",
    ],
  },
  {
    code: "HR",
    name: "Haryana",
    cities: [
      "Faridabad",
      "Gurgaon",
      "Panipat",
      "Ambala",
      "Yamunanagar",
      "Rohtak",
      "Hisar",
      "Karnal",
      "Sonipat",
      "Panchkula",
    ],
  },
  {
    code: "HP",
    name: "Himachal Pradesh",
    cities: [
      "Shimla",
      "Solan",
      "Dharamshala",
      "Mandi",
      "Palampur",
      "Baddi",
      "Nahan",
      "Kullu",
      "Hamirpur",
      "Una",
    ],
  },
  {
    code: "JH",
    name: "Jharkhand",
    cities: [
      "Ranchi",
      "Jamshedpur",
      "Dhanbad",
      "Bokaro",
      "Deoghar",
      "Phusro",
      "Hazaribagh",
      "Giridih",
      "Ramgarh",
      "Medininagar",
    ],
  },
  {
    code: "KA",
    name: "Karnataka",
    cities: [
      "Bangalore",
      "Mysore",
      "Hubli",
      "Mangalore",
      "Belgaum",
      "Gulbarga",
      "Davanagere",
      "Bellary",
      "Bijapur",
      "Shimoga",
    ],
  },
  {
    code: "KL",
    name: "Kerala",
    cities: [
      "Thiruvananthapuram",
      "Kochi",
      "Kozhikode",
      "Kollam",
      "Thrissur",
      "Alappuzha",
      "Palakkad",
      "Kannur",
      "Kasaragod",
      "Kottayam",
    ],
  },
  {
    code: "MP",
    name: "Madhya Pradesh",
    cities: [
      "Indore",
      "Bhopal",
      "Jabalpur",
      "Gwalior",
      "Ujjain",
      "Sagar",
      "Dewas",
      "Satna",
      "Ratlam",
      "Rewa",
    ],
  },
  {
    code: "MH",
    name: "Maharashtra",
    cities: [
      "Mumbai",
      "Pune",
      "Nagpur",
      "Thane",
      "Nashik",
      "Aurangabad",
      "Solapur",
      "Amravati",
      "Kolhapur",
      "Sangli",
    ],
  },
  {
    code: "MN",
    name: "Manipur",
    cities: [
      "Imphal",
      "Thoubal",
      "Bishnupur",
      "Churachandpur",
      "Ukhrul",
      "Senapati",
      "Tamenglong",
      "Chandel",
      "Jiribam",
      "Kangpokpi",
    ],
  },
  {
    code: "ML",
    name: "Meghalaya",
    cities: [
      "Shillong",
      "Tura",
      "Nongpoh",
      "Jowai",
      "Baghmara",
      "Nongstoin",
      "Resubelpara",
      "Ampati",
      "Williamnagar",
      "Khliehriat",
    ],
  },
  {
    code: "MZ",
    name: "Mizoram",
    cities: [
      "Aizawl",
      "Lunglei",
      "Saiha",
      "Champhai",
      "Kolasib",
      "Serchhip",
      "Mamit",
      "Lawngtlai",
      "Saitual",
      "Khawzawl",
    ],
  },
  {
    code: "NL",
    name: "Nagaland",
    cities: [
      "Kohima",
      "Dimapur",
      "Mokokchung",
      "Tuensang",
      "Wokha",
      "Zunheboto",
      "Phek",
      "Kiphire",
      "Longleng",
      "Peren",
    ],
  },
  {
    code: "OR",
    name: "Odisha",
    cities: [
      "Bhubaneswar",
      "Cuttack",
      "Rourkela",
      "Berhampur",
      "Sambalpur",
      "Puri",
      "Balasore",
      "Bhadrak",
      "Baripada",
      "Jharsuguda",
    ],
  },
  {
    code: "PB",
    name: "Punjab",
    cities: [
      "Ludhiana",
      "Amritsar",
      "Jalandhar",
      "Patiala",
      "Bathinda",
      "Mohali",
      "Firozpur",
      "Batala",
      "Pathankot",
      "Moga",
    ],
  },
  {
    code: "RJ",
    name: "Rajasthan",
    cities: [
      "Jaipur",
      "Jodhpur",
      "Kota",
      "Bikaner",
      "Udaipur",
      "Ajmer",
      "Bhilwara",
      "Alwar",
      "Bharatpur",
      "Sikar",
    ],
  },
  {
    code: "SK",
    name: "Sikkim",
    cities: [
      "Gangtok",
      "Namchi",
      "Gyalshing",
      "Mangan",
      "Singtam",
      "Jorethang",
      "Nayabazar",
      "Rangpo",
      "Yuksom",
      "Pakyong",
    ],
  },
  {
    code: "TN",
    name: "Tamil Nadu",
    cities: [
      "Chennai",
      "Coimbatore",
      "Madurai",
      "Tiruchirappalli",
      "Salem",
      "Tirunelveli",
      "Tiruppur",
      "Vellore",
      "Erode",
      "Thoothukudi",
    ],
  },
  {
    code: "TG",
    name: "Telangana",
    cities: [
      "Hyderabad",
      "Warangal",
      "Nizamabad",
      "Khammam",
      "Karimnagar",
      "Ramagundam",
      "Mahbubnagar",
      "Nalgonda",
      "Adilabad",
      "Suryapet",
    ],
  },
  {
    code: "TR",
    name: "Tripura",
    cities: [
      "Agartala",
      "Dharmanagar",
      "Udaipur",
      "Kailashahar",
      "Belonia",
      "Khowai",
      "Pratapgarh",
      "Ranirbazar",
      "Sonamura",
      "Kumarghat",
    ],
  },
  {
    code: "UP",
    name: "Uttar Pradesh",
    cities: [
      "Lucknow",
      "Kanpur",
      "Ghaziabad",
      "Agra",
      "Varanasi",
      "Meerut",
      "Allahabad",
      "Bareilly",
      "Aligarh",
      "Moradabad",
    ],
  },
  {
    code: "UT",
    name: "Uttarakhand",
    cities: [
      "Dehradun",
      "Haridwar",
      "Roorkee",
      "Haldwani",
      "Rudrapur",
      "Kashipur",
      "Rishikesh",
      "Kotdwar",
      "Ramnagar",
      "Pithoragarh",
    ],
  },
  {
    code: "WB",
    name: "West Bengal",
    cities: [
      "Kolkata",
      "Howrah",
      "Durgapur",
      "Asansol",
      "Siliguri",
      "Malda",
      "Barrackpore",
      "Kharagpur",
      "Haldia",
      "Krishnanagar",
    ],
  },
];

export const getStateByCode = (code: string): State | undefined => {
  return INDIAN_STATES.find((state) => state.code === code);
};

export const getStateByName = (name: string): State | undefined => {
  return INDIAN_STATES.find((state) => state.name === name);
};

export const getCitiesByState = (stateName: string): string[] => {
  const state = getStateByName(stateName);
  return state ? state.cities : [];
};

export const getAllStates = (): string[] => {
  return INDIAN_STATES.map((state) => state.name);
};
