import AsyncStorage from "@react-native-async-storage/async-storage";
import { User, SignupData, AuthResponse } from "@/types";

const KEYS = {
  PHONE_VERIFICATION: "phone_verification",
  OTP_DATA: "otp_data",
};

export const phoneAuthService = {
  async sendOtp(
    phone: string,
    method: "sms" | "call" = "sms",
  ): Promise<boolean> {
    try {
      // Simulate sending OTP
      const otp = "123456"; // In production, this would be generated by backend
      const otpData = {
        phone,
        otp,
        expiresAt: Date.now() + 5 * 60 * 1000, // 5 minutes
        attempts: 0,
      };

      await AsyncStorage.setItem(KEYS.OTP_DATA, JSON.stringify(otpData));

      // Simulate network delay
      await new Promise((resolve) => setTimeout(resolve, 1500));

      return true;
    } catch (error) {
      console.error("Error sending OTP:", error);
      return false;
    }
  },

  async verifyOtp(phone: string, enteredOtp: string): Promise<boolean> {
    try {
      const otpDataStr = await AsyncStorage.getItem(KEYS.OTP_DATA);
      if (!otpDataStr) return false;

      const otpData = JSON.parse(otpDataStr);

      // Check if OTP is for the right phone number
      if (otpData.phone !== phone) return false;

      // Check if OTP has expired
      if (Date.now() > otpData.expiresAt) return false;

      // Check if too many attempts
      if (otpData.attempts >= 3) return false;

      // Check OTP match
      if (otpData.otp === enteredOtp) {
        // Clear OTP data after successful verification
        await AsyncStorage.removeItem(KEYS.OTP_DATA);
        return true;
      } else {
        // Increment attempts
        otpData.attempts += 1;
        await AsyncStorage.setItem(KEYS.OTP_DATA, JSON.stringify(otpData));
        return false;
      }
    } catch (error) {
      console.error("Error verifying OTP:", error);
      return false;
    }
  },

  async isPhoneVerified(phone: string): Promise<boolean> {
    try {
      const verifiedPhonesStr = await AsyncStorage.getItem(
        KEYS.PHONE_VERIFICATION,
      );
      if (!verifiedPhonesStr) return false;

      const verifiedPhones = JSON.parse(verifiedPhonesStr);
      return verifiedPhones.includes(phone);
    } catch (error) {
      console.error("Error checking phone verification:", error);
      return false;
    }
  },

  async markPhoneAsVerified(phone: string): Promise<boolean> {
    try {
      const verifiedPhonesStr = await AsyncStorage.getItem(
        KEYS.PHONE_VERIFICATION,
      );
      let verifiedPhones = verifiedPhonesStr
        ? JSON.parse(verifiedPhonesStr)
        : [];

      if (!verifiedPhones.includes(phone)) {
        verifiedPhones.push(phone);
        await AsyncStorage.setItem(
          KEYS.PHONE_VERIFICATION,
          JSON.stringify(verifiedPhones),
        );
      }

      return true;
    } catch (error) {
      console.error("Error marking phone as verified:", error);
      return false;
    }
  },

  async validateIndianPhone(phone: string): Promise<boolean> {
    // Remove all non-digit characters
    const cleanPhone = phone.replace(/\D/g, "");

    // Check if it's exactly 10 digits and starts with valid Indian mobile prefixes
    if (cleanPhone.length === 10) {
      const validPrefixes = ["6", "7", "8", "9"];
      return validPrefixes.includes(cleanPhone[0]);
    }

    return false;
  },

  async formatPhoneForDisplay(phone: string): string {
    const cleanPhone = phone.replace(/\D/g, "");

    if (cleanPhone.length === 10) {
      return `+91-${cleanPhone.slice(0, 5)}-${cleanPhone.slice(5)}`;
    }

    return phone;
  },

  async formatPhoneForStorage(phone: string): string {
    // Remove all non-digit characters and ensure it starts with country code
    const cleanPhone = phone.replace(/\D/g, "");

    if (cleanPhone.length === 10) {
      return `91${cleanPhone}`; // Add India country code
    } else if (cleanPhone.length === 12 && cleanPhone.startsWith("91")) {
      return cleanPhone;
    }

    return phone;
  },

  async clearOtpData(): Promise<void> {
    try {
      await AsyncStorage.removeItem(KEYS.OTP_DATA);
    } catch (error) {
      console.error("Error clearing OTP data:", error);
    }
  },

  async getOtpTimeRemaining(phone: string): Promise<number> {
    try {
      const otpDataStr = await AsyncStorage.getItem(KEYS.OTP_DATA);
      if (!otpDataStr) return 0;

      const otpData = JSON.parse(otpDataStr);

      if (otpData.phone !== phone) return 0;

      const timeRemaining = Math.max(0, otpData.expiresAt - Date.now());
      return Math.floor(timeRemaining / 1000); // Return seconds
    } catch (error) {
      console.error("Error getting OTP time remaining:", error);
      return 0;
    }
  },
};
